# Generated by Django 2.2.11 on 2020-03-13 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Phone Number')),
                ('inv_address', models.CharField(blank=True, max_length=255, verbose_name='Invoice Address')),
                ('inv_city', models.CharField(blank=True, max_length=100, verbose_name='Invoice City')),
                ('inv_state', models.CharField(blank=True, max_length=100, verbose_name='Invoice State')),
                ('inv_pin', models.IntegerField(blank=True, verbose_name='Invoice Pin')),
                ('del_address', models.CharField(blank=True, max_length=255, verbose_name='Delivery Address')),
                ('del_city', models.CharField(blank=True, max_length=100, verbose_name='Delivery City')),
                ('del_state', models.CharField(blank=True, max_length=100, verbose_name='Delivery State')),
                ('del_pin', models.IntegerField(blank=True, verbose_name='Delivery Pin')),
                ('user_uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
