# Generated by Django 2.2.11 on 2020-03-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userdetails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Full Name')),
                ('degree', models.CharField(blank=True, max_length=255, verbose_name='Degree')),
                ('stream', models.CharField(blank=True, max_length=255, verbose_name='Stream')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Current Location of the Candidate')),
                ('resume', models.FileField(blank=True, help_text='Upload PDF File Only', null=True, upload_to='dashboard/%Y/%m/')),
            ],
        ),
    ]
