# Generated by Django 2.2.11 on 2020-03-19 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_admindetails_candidatedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminDetails',
        ),
    ]
