# Generated by Django 2.2.11 on 2020-03-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_delete_admindetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='resume',
            field=models.FileField(help_text='Upload PDF File Only', upload_to='dashboard/%Y/%m/'),
        ),
    ]
