# Generated by Django 2.2.11 on 2020-03-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200319_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=255, verbose_name='Subscription Name')),
                ('price', models.CharField(max_length=255, verbose_name='Subscription Price')),
                ('no_resume', models.IntegerField(verbose_name='No. of Resume User can Access')),
            ],
        ),
    ]
