# Generated by Django 2.2.11 on 2020-03-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200324_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.PositiveIntegerField(max_length=255, verbose_name='Subscription Price'),
        ),
    ]
